defmodule PhoenixKit.Integration.ActivityOrderDeterminismTest do
  @moduledoc """
  Regression test for the `Activity.list/1` / `Activity.recent/1` tie-break bug:
  both sorted by `inserted_at` alone, a second-resolution column with no
  uniqueness constraint. Two entries logged within the same second tied, and
  Postgres was free to return them in whichever order its query plan
  happened to land on — not necessarily the order they were actually
  created in.

  A tie cannot be reproduced by timing two real `Activity.log/1` calls close
  together — it has to be forced by inserting two rows with the SAME
  `inserted_at` explicitly (bypassing the schema's autogenerated timestamp
  via `insert_all/3`, since `Entry.changeset/2` does not cast it).

  NOT RUN in this environment (no reachable Postgres — see the
  `CORE-activity-order` report for the DB-free proof used instead, which
  covers the *mechanism* of the fix: the compiled `ORDER BY` SQL of these
  same two functions). This file only proves it compiles here; the assertions
  below have not been executed against a real database.
  """
  use PhoenixKit.DataCase, async: true

  alias PhoenixKit.Activity
  alias PhoenixKit.Activity.Entry

  defp insert_tied!(uuid, inserted_at) do
    {1, _} =
      Repo.insert_all(Entry, [
        %{
          uuid: uuid,
          action: "activity_order_determinism_test.tied",
          module: "activity_order_determinism_test",
          metadata: %{},
          inserted_at: inserted_at
        }
      ])

    uuid
  end

  test "recent/1 puts the truly-last entry first even when inserted_at ties to the second" do
    tied_at = DateTime.utc_now() |> DateTime.truncate(:second)
    ms = DateTime.to_unix(tied_at, :millisecond)

    # Same second, different (and later) millisecond — UUIDv7's leading 48
    # bits are the millisecond timestamp, so `later_uuid > earlier_uuid`
    # byte-wise, exactly matching Postgres's `uuid` column comparison.
    earlier_uuid = UUIDv7.generate(ms)
    later_uuid = UUIDv7.generate(ms + 1)

    insert_tied!(earlier_uuid, tied_at)
    insert_tied!(later_uuid, tied_at)

    entries = Activity.recent(2)

    assert Enum.map(entries, & &1.uuid) == [later_uuid, earlier_uuid]
  end

  test "list/1 puts the truly-last entry first even when inserted_at ties to the second" do
    tied_at = DateTime.utc_now() |> DateTime.truncate(:second)
    ms = DateTime.to_unix(tied_at, :millisecond)

    earlier_uuid = UUIDv7.generate(ms)
    later_uuid = UUIDv7.generate(ms + 1)

    insert_tied!(earlier_uuid, tied_at)
    insert_tied!(later_uuid, tied_at)

    result =
      Activity.list(module: "activity_order_determinism_test", per_page: 2, preload: [])

    assert Enum.map(result.entries, & &1.uuid) == [later_uuid, earlier_uuid]
  end
end
